# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryname', models.CharField(default='', max_length=254)),
                ('aboutthegallery', models.TextField()),
                ('openinghours', models.TextField()),
                ('adress', models.TextField()),
                ('galleryimage', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techniques', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(default='', max_length=254)),
                ('techniques', models.CharField(default='', max_length=254)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='galleryart',
            name='artistname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='exhibit.GalleryArtist', verbose_name='ArtinGallery'),
        ),
        migrations.AddField(
            model_name='galleryart',
            name='galleryname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='exhibit.Gallery', verbose_name='Galleries'),
        ),
    ]
