# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0003_auto_20200401_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryart',
            old_name='image',
            new_name='artimage',
        ),
        migrations.AlterField(
            model_name='galleryart',
            name='artistname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='exhibit.GalleryArtist', verbose_name='Artist_Name'),
        ),
    ]
