# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0004_auto_20200401_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryart',
            name='artname',
            field=models.CharField(default='Artname', max_length=254),
        ),
    ]
