# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('artistname', models.CharField(default='', max_length=254)),
                ('hall', models.CharField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
