# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-15 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20200315_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitions',
            options={},
        ),
    ]
