# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibit', '0007_auto_20200402_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('galleryart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibit.GalleryArt')),
            ],
        ),
    ]
