# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0007_auto_20200402_1238'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibit.GalleryArt')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote')),
            ],
        ),
    ]
