# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-13 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votecounting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='galleryart',
            new_name='artname',
        ),
    ]
